version: '3.4'

services:
  app:
    container_name: nest_todos
    restart: always
    build: .
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'